app:
  security:
    jwt:
      authtype: Bearer
      rtexpirationmins: 4320
      atexpirationmins: 360
      uri:

    header: jjh
    authentication:
      type: DBBASED
    key:
      keytype: shared
      signingsecret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: app@digitalsherpa.ai
    password: 123edc#EDC
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://security_hg1k_user.dpg-cq8okgbv2p9s73aq64k0-a.oregon-postgres.render.com/security_hg1k
    username: security_hg1k_user
    password: XXtOT5Q33yhRWrNFiaDlAElGKAMxLJ9n
    hikari:
      minimumIdle: 0
      maximumPoolSize: 3
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

